db_common: &db_common
  adapter: sqlite3
  timeout: 5000
  pool: 5

development:
  <<: *db_common
  database: db/development.sqlite3

test:
  <<: *db_common
  database: db/test.sqlite3

production:
  <<: *db_common
  database: db/production.sqlite3
