secrets_commom: &secrets_common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  base: <%= ENV["SECRET_KEY_BASE"] %>
  salt: <%= ENV["SECRET_SALT"] %>
  github:
    key: <%= ENV["GITHUB_KEY"] %>
    secret: <%= ENV["GITHUB_SECRET"] %>

development:
  <<: *secrets_common

test:
  <<: *secrets_common

production:
  <<: *secrets_common
